[package]
name = "crusty"
version = "0.1.0"
authors = ["Lasse <lasse.moeldrup@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[profile.bench]
lto = true

[dependencies]
num_enum = "0.4.3"
bitintr = "0.3.0"
arrayvec = "0.5.1"
parking_lot = "0.10.2"
lazy_static = "1.4.0"
take-until = "0.1.0"
rand = { version = "0.7.3", features = ["small_rng"] }

[dev-dependencies]
criterion = "0.3"
serde_json = "1.0"

[[bench]]
name = "my_benchmark"
harness = false